### ISSUE TITLE
Find a way to delete all buffers

### ISSUE THREAD

**Issue by geoffreyvanwyk** [geoffreyvanwyk/dotnvim#15]
See how LazyVim or AstroNvim does it. This issue, like a bill in America's congress, all of a sudden all has to do with adding `<leader>b` key mappings for the following commands: 

- [x] Delete all buffers
- [ ] <strike>Delete buffer without closing window</strike>
- [x] Add an empty buffer
- [x] Switch to next _modified_ buffer

**Comment by geoffreyvanwyk** [comment]
### Subtask: Delete buffer without closing window

I found article [Deleting a buffer without closing the window](https://vim.fandom.com/wiki/Deleting_a_buffer_without_closing_the_window) on the Vim Tips Wiki. The main content of the article promotes a `:Bclose` command, but the first option they gave looks good enough:

> One option is to first switch to another buffer (:bp, :bn, or :b#, for instance) and then delete the first (alternate) buffer with :bd#.

**Comment by geoffreyvanwyk** [comment]
### Subtask: Delete all buffers

According to [Vim Help](https://vimdoc.sourceforge.net/htmldoc/windows.html#:bdelete), command `:N,Mbdelete` is available. `N,M` is a range of buffer numbers. With the `:%substitute` command, the `%` range means everything. After experimenting, `%` also applies to `:%bdelte`.

**Comment by geoffreyvanwyk** [comment]
### Subtask: Add an empty buffer

An empty buffer is useful if you just want to type something for testing purposes without necessarily needing to save it to file. Commands to map are: 

- [x] `:enew` to add empty buffer to current window. 
- [x] `:vnew` to add empty buffer to vertical split.

I rarely use horizontal splits (created with `:new`).

**Comment by geoffreyvanwyk** [comment]
### Subtask: Switch to next modified buffer

Map the `:bmodified` command.

**Comment by geoffreyvanwyk** [comment]
I read through most of [Vim buffer FAQ](https://vim.fandom.com/wiki/Vim_buffer_FAQ).

**Comment by geoffreyvanwyk** [comment]
### Subtask: Delete buffer without closing window

I implemented this, but it does not work if the buffer appears in more than one window. I decided to forget about it. Based on web searches, many people would like this feature.
